'use client';
import {useEffect,useRef,useState} from 'react';
import Image from 'next/image';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {portfolio} from '@/data/portfolio';

export function AutomotiveShowcase({compact=false}:{compact?:boolean}){
  const root=useRef<HTMLDivElement>(null);const[progress,setProgress]=useState(0);const[reduced,setReduced]=useState(false);
  useEffect(()=>{const media=matchMedia('(prefers-reduced-motion: reduce)');let frame=0;const measure=()=>{frame=0;if(!root.current)return;const rect=root.current.getBoundingClientRect();const travel=Math.max(1,rect.height-innerHeight+110);const value=Math.max(0,Math.min(1,(110-rect.top)/travel));setProgress(media.matches?0:value);};const update=()=>{if(!frame)frame=requestAnimationFrame(measure);};const preferences=()=>{setReduced(media.matches);update();};preferences();addEventListener('scroll',update,{passive:true});addEventListener('resize',update);media.addEventListener('change',preferences);return()=>{cancelAnimationFrame(frame);removeEventListener('scroll',update);removeEventListener('resize',update);media.removeEventListener('change',preferences);};},[]);
  const chapter=progress<.34?0:progress<.7?1:2;
  const chapters=[{tag:'01 / THE FIRST IMPRESSION',title:'DRIVEN BY',accent:'DESIRE.',copy:'An automotive experience with presence. Precise lines. Unmistakable attitude.'},{tag:'02 / EVERY DETAIL COUNTS',title:'CONTROL.',accent:'WITHOUT COMPROMISE.',copy:'A closer look at the machine. Design that moves with you, one scroll at a time.'},{tag:'03 / YOUR NEXT CHAPTER',title:'THE ROAD',accent:'IS YOURS.',copy:'Take the next step. A clear route from discovery to a conversation.'}];
  const c=chapters[chapter];return <div ref={root} className={'auto-scroll '+(compact?'auto-compact ':'')+(reduced?'auto-reduced':'')} data-progress={progress.toFixed(3)}>
    <div className="auto-scene"><nav className="auto-nav" aria-label="Monsanto Auto example"><strong>MONSANTO<span>AUTO</span></strong><span>EXCEPTIONAL BY DESIGN</span><a href="/audit?service=Automotive%20website">Build a site like this</a></nav>
    <div className="auto-copy"><p className="auto-kicker">{c.tag}</p><h2>{c.title}<br/><span>{c.accent}</span></h2><p>{c.copy}</p></div><div className="auto-disc" aria-hidden="true" style={{transform:`translateX(${progress*30}%) scale(${.75+progress*.4})`}}/>
    <div className="auto-car" style={{transform:`translate3d(${(progress-.5)*35}%,${Math.sin(progress*Math.PI)*-12}%,0) scale(${.78+progress*.3}) rotate(${(progress-.5)*-3}deg)`}}><Image src="/portfolio/car.webp" width={1536} height={1024} alt="Silver sports coupe moving across the Monsanto Auto concept as you scroll" priority={false}/></div>
    <div className="auto-floor" aria-hidden="true"/><div className="auto-bottom"><span>{reduced?'MOTION REDUCED': 'SCROLL TO DRIVE THE EXPERIENCE'}</span><div className="auto-progress" aria-hidden="true"><span style={{width:progress*100+'%'}}/></div><span>0{chapter+1} / 03</span></div>
    </div></div>;
}

export function PortfolioGallery({teaser=false}:{teaser?:boolean}){const cats=['All','Automotive','Service business','Brand & design','E-commerce','Web app'];const cards=(category:string)=><div className="portfolio-grid">{portfolio.filter(p=>category==='All'||p.category===category).slice(0,teaser?3:portfolio.length).map((p,i)=><a className={'visual-project visual-'+p.slug} href={'/portfolio/'+p.slug} key={p.slug}><div className="visual-frame"><div className="browser-chrome" aria-hidden="true"><span>● ● ●</span><span>{p.name.toLowerCase().replace(/[^a-z]/g,'')}.concept</span></div><div className={'visual-hero visual-tone-'+p.tone}><Image src={p.image} width={1200} height={800} alt={p.alt} className="visual-art"/><div className="visual-overlay"/><div className="visual-type"><span>{p.name}</span><strong>{p.headline}</strong><small>{p.kind==='auto'?'SCROLL-DRIVEN AUTOMOTIVE':'EXPLORE THE HOMEPAGE'}</small></div>{p.kind==='dashboard'&&<div className="visual-dashboard" aria-hidden="true"><div>Projects <b>12</b></div><div>In progress <b>06</b></div><div>Ready <b>04</b></div></div>}</div></div><div className="visual-caption"><div><p className="eyebrow">{String(i+1).padStart(2,'0')} / {p.category.toUpperCase()}</p><h3>{p.name}</h3><p>{p.detail}</p></div><span className="view-concept">View concept</span></div></a>)}</div>;return teaser?cards('All'):<Tabs defaultValue="All"><TabsList className="portfolio-tabs portfolio-filters">{cats.map(c=><TabsTrigger key={c} value={c}>{c}</TabsTrigger>)}</TabsList>{cats.map(c=><TabsContent key={c} value={c}>{cards(c)}</TabsContent>)}</Tabs>}

export function ExampleHomepage({slug}:{slug:string}){const p=portfolio.find(p=>p.slug===slug)!;const[bag,setBag]=useState(0);const[season,setSeason]=useState('Trail');const[project,setProject]=useState('All');if(p.kind==='auto')return <AutomotiveShowcase/>;if(p.kind==='dashboard')return <div className="example-app"><aside className="example-sidebar"><b>rally<span>®</span></b><a href="#example-overview">Overview</a><a href="#example-projects">Projects</a><a href="#example-notes">Notes</a><span>YOUR WORK, IN MOTION.</span></aside><div className="example-workspace"><div className="workspace-top"><span>Workspace / Overview</span><span className="concept-pill">Interactive concept</span></div><div id="example-overview" className="workspace-intro"><div><p>MONDAY, MADE SIMPLE.</p><h2>Good morning.<br/>Let’s move things forward.</h2></div><Image src={p.image} width={600} height={400} alt={p.alt}/></div><div className="workspace-metrics"><article><span>Active projects</span><strong>12</strong><small>Sample workspace</small></article><article><span>In progress</span><strong>06</strong><small>Ideas becoming real</small></article><article><span>Ready to launch</span><strong>04</strong><small>The next chapter</small></article></div><section id="example-projects"><h3>Your projects</h3><Tabs value={project} onValueChange={setProject}><TabsList><TabsTrigger value="All">All projects</TabsTrigger><TabsTrigger value="Design">Design</TabsTrigger><TabsTrigger value="Development">Development</TabsTrigger></TabsList><TabsContent value={project}><div className="demo-project-rows">{[{n:'Brand refresh',type:'Design',status:'In review'},{n:'Storefront experience',type:'Development',status:'In progress'},{n:'Campaign direction',type:'Design',status:'Ready'}].filter(x=>project==='All'||x.type===project).map(x=><div key={x.n}><b>{x.n}</b><span>{x.type}</span><em>{x.status}</em></div>)}</div></TabsContent></Tabs></section><section id="example-notes" className="workspace-note"><h3>Everything in one place.</h3><p>A sample of the kind of workspace we can build around your business. Project information here is illustrative.</p><a href="/audit?service=Custom%20web%20app">Discuss your own workspace</a></section></div></div>;
  return <div className={'example-home example-'+p.kind}><nav className="example-nav" aria-label={p.name+' concept navigation'}><b>{p.name}<span>®</span></b><div><a href="#example-story">{p.kind==='studio'?'Studio':p.kind==='commerce'?'Collection':'Our approach'}</a><a href="#example-offer">{p.kind==='commerce'?'Shop':p.kind==='wellness'?'Treatments':'Discover'}</a></div><a href="/audit">{p.kind==='commerce'?'Bag ('+bag+')':'Let’s connect'}</a></nav>
    <section className="example-hero"><Image src={p.image} width={1536} height={1024} alt={p.alt} className="example-hero-art"/><div className="example-hero-overlay"/><div className="example-hero-copy"><p>{p.kicker}</p><h2>{p.headline}</h2><span>{p.description}</span><a href="#example-offer" className="example-button">{p.action}</a></div><span className="example-edition">{p.edition}</span></section>
    <section className="example-story" id="example-story"><p>{p.storyLabel}</p><h2>{p.storyTitle}</h2><span>{p.story}</span></section>
    {p.kind==='commerce'?<section className="example-products" id="example-offer"><div><p>CHOOSE YOUR NEXT CHAPTER</p><h2>The outside<br/>is calling.</h2><Tabs value={season} onValueChange={setSeason}><TabsList><TabsTrigger value="Trail">Trail</TabsTrigger><TabsTrigger value="Weekend">Weekend</TabsTrigger><TabsTrigger value="Everyday">Everyday</TabsTrigger></TabsList><TabsContent value={season}><h3>{season==='Trail'?'Summit 28L':season==='Weekend'?'Roam 32L':'Everyday 18L'}</h3><p>{season==='Trail'?'A technical pack for the long way around.':season==='Weekend'?'More room for a little escape.':'Your essentials. Ready for anything.'}</p><button className="example-button" onClick={()=>setBag(v=>v+1)}>Add to demo bag</button><p role="status" className="demo-bag-status">{bag>0?bag+' sample '+(bag===1?'item':'items')+' in your demo bag. No purchase or checkout.':'Try the product selector and sample bag.'}</p></TabsContent></Tabs></div><Image src={p.image} width={900} height={600} alt={p.alt}/></section>:<section className="example-offers" id="example-offer">{p.offers.map((o,i)=><article key={o.title}><span>0{i+1}</span><h3>{o.title}</h3><p>{o.copy}</p><a href={'/audit?service='+encodeURIComponent(p.name+' inspired website')}>{o.action}</a></article>)}</section>}
    <section className="example-ending"><p>{p.endingLabel}</p><h2>{p.ending}</h2><a href={'/audit?service='+encodeURIComponent(p.name+' inspired website')} className="example-button">Create your own version</a></section><div className="example-footer"><b>{p.name}</b><span>Original website concept by Code &amp; Chaos</span></div>
  </div>;
}

export function ProjectShowcase({slug}:{slug:string}){const p=portfolio.find(p=>p.slug===slug)!;return <><div className="showcase-bar wrap"><div><a href="/portfolio" className="text-link">All portfolio examples</a><h1>{p.name}</h1><p>{p.category} / Original design concept</p></div><a className="btn secondary" href={'/audit?service='+encodeURIComponent(p.name+' inspired website')}>I like this direction</a></div><ExampleHomepage slug={slug}/><section className="wrap section concept-details"><div><p className="eyebrow">THE IDEA BEHIND THE EXPERIENCE</p><h2>{p.name}</h2><p>{p.detail}</p></div><div><ul className="check-list">{p.features.map(f=><li key={f}>{f}</li>)}</ul><p className="sample-note">An illustrative concept, not commissioned client work. Demo interactions don’t make purchases or appointments.</p></div></section><section className="wrap section"><p className="eyebrow">A DIFFERENT PERSPECTIVE</p><h2>Explore another direction.</h2><div className="related-concepts">{portfolio.filter(x=>x.slug!==slug).map(x=><a href={'/portfolio/'+x.slug} key={x.slug}><span>{x.category}</span><strong>{x.name}</strong></a>)}</div></section></>}
