import {site} from '@/data/site.config';
import {services} from '@/data/services';
import {packages,carePlans} from '@/data/packages';
import {faqs} from '@/data/faq';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
export function JsonLd({data}:{data:unknown}){return <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(data).replace(/</g,'\\u003c')}}/>}
export function BusinessSchema(){return <JsonLd data={{'@context':'https://schema.org','@type':['Organization','ProfessionalService'],'@id':site.origin+'/#business',name:site.name,url:site.origin,telephone:site.tel,logo:site.origin+'/logo.png',description:'Web design, development and local SEO for Florida businesses.',areaServed:{'@type':'State',name:'Florida'}}}/>}
export function FAQSchema(){return <JsonLd data={{'@context':'https://schema.org','@type':'FAQPage',mainEntity:faqs.map(f=>({'@type':'Question',name:f.q,acceptedAnswer:{'@type':'Answer',text:f.a}}))}}/>}
export function Breadcrumbs({items}:{items:{name:string,href:string}[]}){const all=[{name:'Home',href:'/'},...items];return <><nav className="breadcrumbs wrap" aria-label="Breadcrumb">{all.map((c,i)=><span key={c.href}>{i>0&&<span aria-hidden="true"> / </span>}<a href={c.href} aria-current={i===all.length-1?'page':undefined}>{c.name}</a></span>)}</nav><JsonLd data={{'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:all.map((c,i)=>({'@type':'ListItem',position:i+1,name:c.name,item:site.origin+c.href}))}}/></>}
export function PageHero({eyebrow,title,description}:{eyebrow:string,title:string,description:string}){return <section className="page-hero wrap"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{description}</p></section>}
export function CTA({title='Let’s build your next chapter.'}:{title?:string}){return <section className="cta-band"><div className="wrap"><div><p className="eyebrow">GOOD IDEAS DESERVE A GREAT WEBSITE</p><h2>{title}</h2></div><div className="actions"><a className="btn primary" href="/audit">Get a free website audit</a><a className="btn secondary" href={'tel:'+site.tel}>Call {site.phone}</a></div></div></section>}
export function ServicesGrid(){return <div className="grid three">{services.map((s,i)=><a key={s.slug} className="service-card reveal" href={'/services/'+s.slug}><span className="card-number">{String(i+1).padStart(2,'0')} / {i%2?'CHAOS':'CODE'}</span><h3>{s.name}</h3><p>{s.short}</p><span className="text-link">Explore service</span></a>)}</div>}
export function PackageCards({compact=false}:{compact?:boolean}){return <div className={'grid '+(compact?'three':'four')}>{packages.slice(0,compact?3:4).map(p=><article key={p.name} className={'package-card '+(p.featured?'featured':'')}><div className="package-top">{p.featured?<span className="popular">MOST POPULAR</span>:<span className="package-label">WEBSITE BUILD</span>}</div><h3>{p.name}</h3><p>{p.tag}</p><strong className="price">{p.price?'From $'+p.price.toLocaleString('en-US'):'Request a quote'}</strong><p className="sample-note">One-time build · USD</p><p className="package-for">For {p.for.toLowerCase()}</p><ul className="check-list">{p.features.map(f=><li key={f}>{f}</li>)}</ul><a className={'btn '+(p.featured?'primary':'secondary')} href={'/audit?package='+encodeURIComponent(p.name)}>Discuss {p.name}</a></article>)}</div>}
export function CareCards(){return <div className="grid three">{carePlans.map(p=><article className={'package-card '+(p.featured?'featured':'')} key={p.name}><div className="package-top">{p.featured?<span className="popular">MOST POPULAR</span>:<span className="package-label">MONTHLY CARE</span>}</div><h3>{p.name}</h3><p>Ongoing support, scoped to your website.</p><strong className="price">From {'$'+p.price.toLocaleString('en-US')}/month</strong><ul className="check-list">{p.features.map(f=><li key={f}>{f}</li>)}</ul><a className="btn secondary" href={'/audit?package='+encodeURIComponent(p.name)}>Discuss this plan</a></article>)}</div>}
export function Comparison(){const rows=[['Pages','1–3','5–8','10+ / store','Scoped'],['Design','Focused landing site','Custom design','Advanced design','Custom'],['On-page SEO','Basic','Full','Advanced + locations','Scoped'],['Blog','Optional','Included','Included','Scoped'],['Google Business Profile','Optional','Setup','Scoped','Scoped'],['AI chatbot','Optional','Optional','Included','Scoped'],['Revision rounds','1','2','3','Scoped']];return <div className="table-wrap"><Table><TableHeader><TableRow><TableHead>Included</TableHead>{packages.map(p=><TableHead key={p.name}>{p.name}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map(([label,...cells])=><TableRow key={label}><TableCell className="font-semibold">{label}</TableCell>{cells.map((c,i)=><TableCell key={i}>{c}</TableCell>)}</TableRow>)}</TableBody></Table></div>}
export function Process(){return <section className="wrap section reveal"><div className="section-heading"><div><p className="eyebrow">FROM IDEA TO IMPACT</p><h2>A clear process.<br/>Room for possibility.</h2></div><p>You bring the ambition. We bring a plan, creative direction, and the technical work to make it real.</p></div><div className="grid four process">{[['01','Discover','We get to know your business, audience, and what the website needs to achieve.'],['02','Design','We shape the experience and visual direction, with clear points for your feedback.'],['03','Develop','We build the pages and functionality, then check the important customer journeys.'],['04','Launch & grow','We launch with a practical handoff and a care plan if you need ongoing support.']].map(([n,t,d])=><article key={n}><span className="card-number">{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>}
