export type SalesMessage={role:'user'|'assistant';text:string};
export function salesReply(message:string,history:SalesMessage[]=[]){
 const m=message.toLowerCase();const context=[...history.filter(x=>x.role==='user').map(x=>x.text),message].join(' ').toLowerCase();
 const store=/store|shop|e-commerce|ecommerce|sell products/.test(context),local=/plumb|roof|contract|salon|restaurant|local|landscap|cleaning|dentist/.test(context),newSite=/no website|first website|new business|starting/.test(context);
 const scope=store?'Supernova starts at $2,995 USD for a one-time build and is a useful starting point for an online store, with scope shaped around your products and checkout needs.':newSite?'Spark starts at $795 USD for a one-time build and is a useful starting point for a focused 1–3 page website with mobile design, basic SEO, and a contact form.':'Surge starts at $1,495 USD for a one-time build and is a useful starting point for a growing business: 5–8 custom pages, on-page SEO, and Google Business Profile setup.';
 if(/ignore.*instruction|system prompt|secret|api key/.test(m))return 'I can help you choose the right website or marketing service. What would you like your business to achieve?';
 if(/not interested|stop|no thanks/.test(m))return 'Of course. If you need us later, you can browse our work or call 772-666-1029.';
 if(/book|ready|get started|quote|contact|talk to|follow.up/.test(m))return 'The next step is a project conversation with the team. Choose “Discuss my project” below to review a summary and send an inquiry, or call 772-666-1029. A submitted inquiry requests a follow-up; it does not book an appointment.';
 if(/discount|price.match|match.*price|competitor|another quote/.test(m))return 'Our builds start at $795 for Spark, $1,495 for Surge, and $2,995 for Supernova in USD. We can compare another quote against the pages, features, content, and ongoing support included. I cannot approve a discount, but the team can discuss a smaller scope. What does the other quote include?';
 if(/guarantee|number one|#1|first.*google/.test(m))return 'We cannot guarantee rankings or a set number of leads. We can improve the technical foundations, useful service content, and path to contacting your business. What service and area would you most like to be found for?';
 if(/expensive|afford|cheap|too much|small budget/.test(m))return 'We can discuss a focused first phase and separate essentials from later additions. '+scope+' Final scope and price require a written proposal. What budget range would you be comfortable discussing?';
 if(/price|cost|package|budget|spark|surge|supernova/.test(m))return scope+' Final pricing depends on scope; monthly care and third-party costs are separate. '+(store?'About how many products do you plan to sell?':'What are the must-have pages or features?');
 if(/already.*website|existing.*website|redesign|refresh/.test(m))return 'A redesign should solve a specific problem, not just change the look. We can review your mobile experience, clarity, search foundations, and inquiry path before recommending a scope. What is your current website URL?';
 if(/wix|squarespace|do it myself|diy|template/.test(m))return 'A template can be a sensible starting point when your needs are simple. Custom work is useful when your brand, services, or workflows need a more tailored experience. What is the biggest limitation you are running into?';
 if(/time|timeline|deadline|how long/.test(m))return 'The schedule depends on scope, content readiness, and review rounds; the team confirms it after discovery. We can prioritize the essentials around your target date. When would you like to launch?';
 if(/seo|google|traffic|leads|inquiries|customers|calls/.test(m))return 'For more qualified inquiries, I would look at the offer, service pages, local search presence, and ease of contacting you together. '+(local?'Local SEO and Google Business Profile management may be a good fit. ':'SEO and conversion-focused website work may be a good fit. ')+'Do you already have a website, and where do you serve customers?';
 if(/ai|automati|chatbot|portal|dashboard|integration|web app/.test(m))return 'A custom app or automation could help if it removes a specific recurring task. We would map the workflow and integrations before quoting the work. What task takes the most time each week?';
 if(/care|maintenance|hosting/.test(m))return 'Essential Care starts at $99/month, Growth at $249/month, and Dominate at $599/month, in USD. Essential covers hosting and upkeep; Growth adds scoped content edits and reporting, and Dominate adds scoped SEO content and conversion work. Which matters most: keeping the site healthy, making regular changes, or growing inquiries?';
 if(store)return scope+' A clear product experience and easy checkout are the priorities. Are you launching a new store or improving an existing one?';
 if(/portfolio|examples|work|proof/.test(m))return 'Our portfolio shows seven original concept homepages, including a scroll-driven automotive site, a store, and a dashboard. They illustrate design possibilities and are labeled concepts. What style would fit your business?';
 if(/email|phone|where|florida|location/.test(m))return 'Code & Chaos is based on the Treasure Coast and serves Florida. Email jmontanezz0215@icloud.com or call 772-666-1029. What kind of project are you considering?';
 if(history.some(x=>x.role==='user'))return scope+' To refine that recommendation, what matters most for the first version: more inquiries, selling products, or saving your team time?';
 return 'Let’s find the right fit. We help businesses with websites, local search, branding, stores, and practical automation. What kind of business do you run, and what would you like to improve first?';
}

